### ISSUE TITLE
Large trees don't grow properly.

### ISSUE THREAD

**Issue by Falvyu** [CivClassic/RealisticBiomes#18]
2x2 trees don't grow. 

![Big trees not growing](https://i.imgur.com/Mklszkv.png)

The sapling on the NW corner is usually consumed when the tree is supposed to grow. The other are marked as "0.05% grown"

![0% saplings](https://i.imgur.com/ktPAvyG.png)

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/RealisticBiomes/pull/20
