### ISSUE TITLE
clay still has no effect on crop growth 

### ISSUE THREAD

**Issue by TheOrangeWizard** [CivClassic/RealisticBiomes#23]
tested with carrots, melon blocks/stems

unless countdown timer is wrong lmao

**Comment by squareblob** [comment]
I don't think this is a problem with realistic biomes. 

See https://github.com/CivClassic/AnsibleSetup/pull/82

**Comment by TheOrangeWizard** [comment]
just confirmed clay works with wheat so you're right, it's just a config issue

**Comment by Maxopoly** [comment]
Resolved by https://github.com/CivClassic/AnsibleSetup/pull/82
