### ISSUE TITLE
Saplings unexposed to the sky no longer grow with glowstone

### ISSUE THREAD

**Issue by Inframission** [CivClassic/RealisticBiomes#28]

**Comment by Maxopoly** [comment]
As far as I can tell, glowstone isn't configured for any plants. Probably just a config issue, see https://github.com/CivClassic/AnsibleSetup/blob/master/templates/public/plugins/RealisticBiomes/config.yml.j2

**Comment by Diet-Cola** [comment]
^ trees seem to grow on my test server without sunlight just vastly longer than normal

**Comment by wingzero54** [comment]
Greenhouse growth added to config with [this commit](https://github.com/CivClassic/AnsibleSetup/commit/8e54e9d405a6a4edfe1bb811f1bbcb5d3c9ef872#diff-8ae048e6fa551a80a702d1b17b1cc24995f4ab811c1c1dfcef665a2f6a26ebf2).
