### ISSUE TITLE
Harvesting partially grown sugarcane resets the growth timer

### ISSUE THREAD

**Issue by okx-code** [CivClassic/RealisticBiomes#29]
One would expect that sugarcane with a growth time of 12 hours would grow by 2 blocks in the 12 hours.
However, if you harvest it 11 hours in when one block has grown, it take another 6 hours to grow by one block, extending the growth time to 17 hours.

Not sure if this is intentional or not though. If I get confirmation that it isn't intentional, I can look into making a fix myself

**Comment by Maxopoly** [comment]
It's not intentional, but a difficult architectural issue

**Comment by Maxopoly** [comment]
Relevant code is here https://github.com/CivClassic/RealisticBiomes/blob/master/src/main/java/com/untamedears/realisticbiomes/PlantLogicManager.java#L48
