### ISSUE TITLE
Some Biomes have no attached growth rate for any crops.

### ISSUE THREAD

**Issue by mightyoddish** [CivClassic/RealisticBiomes#8]
https://imgur.com/a/9fw2G5D

Noticed some biomes seem to have no available food or plant that can grow (everything is 0%).
The imgur link shows at least 2 of the biomes but I am not sure how many are really effected.

**Comment by specificlanguage** [comment]
modified_wooded_badlands_plateau should be fixed as of last config update -- currently working on figuring out what's wrong with Dark Forests as actually nothing seems to be growing despite not being declared in the config.

**Comment by Protonull** [comment]
Fixed by [this](https://github.com/CivClassic/AnsibleSetup/pull/39).
