### ISSUE TITLE
Limiting tree height is broken

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/RealisticBiomes#9]
Previously you could put glass/fences above the sapling to limit its height. Now the sapling just disappears without any growth in that setup.

**Comment by Diet-Cola** [comment]
What trees is this? On my local test server acacia works fine with limiting height and when being too restrictive just refuses to grow

**Comment by wingzero54** [comment]
Tested and it works fine, lots of changes between issue creation and now so probably fixed at some point along the way
